version: '3.9'

services:
  mlflow-starter-app:
    container_name: mlflow-starter-app
    build:
      context: ./docker/app
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - DEBIAN_VERSION=${DEBIAN_VERSION}
        - MLFLOW_VERSION=${MLFLOW_VERSION}
        - MLFLOW_SERVER_PORT=${MLFLOW_SERVER_PORT}
    image: "nassarx/airbnb-nlp-app:1.0"
    #restart: always
    volumes:
      - ./app:/code/app
      - ./models:/code/app/models
    ports:
      - "80:80"
      - "5678:5678"

  mlflow-starter-notebook:
    container_name: mlflow-starter-notebook
    build:
      context: ./docker/jupyter
      args:
        - JUPYTER_BASE_IMAGE=${JUPYTER_BASE_IMAGE}
        - JUPYTER_BASE_VERSION=${JUPYTER_BASE_VERSION}
    image: "nassarx/mlflow-starter-notebook:1.0"
    ports:
      - "${JUPYTER_HOST_PORT}:${JUPYTER_PORT}"
    environment:
      - GRANT_SUDO="yes"
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    user: "root"
    command: "start-notebook.sh --NotebookApp.token=${JUPYTER_TOKEN}"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./models:${MLFLOW_ARTIFACT_STORE}:rw
    depends_on:
      - mlflow-starter-server

  mlflow-starter-server:
    container_name: mlflow-starter-server
    build:
      context: ./docker/mlflow
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - DEBIAN_VERSION=${DEBIAN_VERSION}
        - MLFLOW_VERSION=${MLFLOW_VERSION}
        - MLFLOW_SERVER_PORT=${MLFLOW_SERVER_PORT}
    image: "nassarx/mlflow-starter-server:1.0"
    environment:
      - MLFLOW_BACKEND_STORE=${MLFLOW_BACKEND_STORE}
      - MLFLOW_ARTIFACT_STORE=${MLFLOW_ARTIFACT_STORE}
    expose:
      - "${MLFLOW_SERVER_PORT}"
    ports:
      - "${MLFLOW_SERVER_HOST_PORT}:${MLFLOW_SERVER_PORT}"
    volumes:
      - ./mlruns:${MLFLOW_BACKEND_DIR}:rw
      - ./models:${MLFLOW_ARTIFACT_STORE}:ro

networks:
  default:
    name: mlflow-starter