version: '3.9'

services:
  jupyter-notebook:
    container_name: ${COMPOSE_PROJECT_NAME}_jupyter-notebook
    build:
      context: ./docker/jupyter
      args:
        - JUPYTER_BASE_IMAGE=${JUPYTER_BASE_IMAGE}
        - JUPYTER_BASE_VERSION=${JUPYTER_BASE_VERSION}
    image: "nassarx/jupyter-notebook:1.0"
    ports:
      - "${JUPYTER_HOST_PORT}:${JUPYTER_PORT}"
    environment:
      - GRANT_SUDO="yes"
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    user: "root"
    command: "start-notebook.sh --NotebookApp.token=${JUPYTER_TOKEN}"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./models:${MLFLOW_ARTIFACT_STORE}:rw
    depends_on:
      - mlflow-server

  mlflow-server:
    container_name: ${COMPOSE_PROJECT_NAME}_mlflow-server
    build:
      context: ./docker/mlflow
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - DEBIAN_VERSION=${DEBIAN_VERSION}
        - MLFLOW_VERSION=${MLFLOW_VERSION}
        - MLFLOW_SERVER_PORT=${MLFLOW_SERVER_PORT}
    image: "nassarx/mlflow-server:1.0"
    environment:
      - MLFLOW_BACKEND_STORE=${MLFLOW_BACKEND_STORE}
      - MLFLOW_ARTIFACT_STORE=${MLFLOW_ARTIFACT_STORE}
    expose:
      - "${MLFLOW_SERVER_PORT}"
    ports:
      - "${MLFLOW_SERVER_HOST_PORT}:${MLFLOW_SERVER_PORT}"
    volumes:
      - ./mlruns:${MLFLOW_BACKEND_DIR}:rw
      - ./models:${MLFLOW_ARTIFACT_STORE}:ro

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_network