version: '3.9'

services:
  mlflow-starter-app:
    container_name: mlflow-starter-app
    build:
      context: ./docker/app
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - DEBIAN_VERSION=${DEBIAN_VERSION}
        - MLFLOW_VERSION=${MLFLOW_VERSION}
        - MLFLOW_SERVER_PORT=${MLFLOW_SERVER_PORT}
    image: "nassarx/airbnb-nlp-app:1.0"
    #restart: always
    volumes:
      - ./app:/code/app
      - ./models:/code/app/models
    ports:
      - "80:80"
      - "5678:5678"

  mlflow-starter-server:
    container_name: mlflow-starter-server
    build:
      context: ./docker/mlflow
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - DEBIAN_VERSION=${DEBIAN_VERSION}
        - MLFLOW_VERSION=${MLFLOW_VERSION}
        - MLFLOW_SERVER_PORT=${MLFLOW_SERVER_PORT}
    image: "nassarx/mlflow-starter-server:1.0"
    environment:
      - MLFLOW_BACKEND_STORE=${MLFLOW_BACKEND_STORE}
      - MLFLOW_ARTIFACT_STORE=${MLFLOW_ARTIFACT_STORE}
    expose:
      - "${MLFLOW_SERVER_PORT}"
    ports:
      - "${MLFLOW_SERVER_HOST_PORT}:${MLFLOW_SERVER_PORT}"
    volumes:
      - ./mlruns:${MLFLOW_BACKEND_DIR}:rw
      - ./models:${MLFLOW_ARTIFACT_STORE}:ro

  mlflow-starter-kedro:
    container_name: mlflow-starter-kedro
    build:
      context: ./docker/kedro
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - DEBIAN_VERSION=${DEBIAN_VERSION}
        - PROJECT_NAME=${PROJECT_NAME}
        - OUTPUT_DIR=${OUTPUT_DIR}
        - REPO_NAME=${REPO_NAME}
        - PYTHON_PACKAGE=${PYTHON_PACKAGE}
    image: "nassarx/kedro_mlflow:1.0"
    volumes:
      - ./kedro_mlflow:/home/kedro/projects
    ports:
      - "8889:8888"
      - "4142:4141"

networks:
  default:
    name: mlflow-starter